In [48]:
#Importando librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [49]:
#Lei mis datos del archivo Spotify
Examen=pd.read_csv('mortalidad.csv')

In [50]:
#Imprimir encabezados
Examen.columns.values.tolist()

['Año de nacimiento',
 'Mes de nacimiento',
 'Descripción del mes de nacimiento',
 'Día de nacimiento',
 'Genero',
 'Clave de la edad',
 'Edad cumplida',
 'Estado conyugal',
 'Descripción del estado conyugal',
 'Entidad de residencia',
 'Descripción de entidad de residencia',
 'Municipio de residencia',
 'Descripción del municipio de residencia',
 'Localidad de residencia',
 'Descripión de la localidad de residencia',
 'Tamaño de localidad',
 'Descripción del tamaño de localidad',
 'Ocupación habitual',
 'Descripción de la ocupación habitual',
 'Escolaridad',
 'Descripción de la escolaridad',
 'Derechiahabiencia',
 'Descrición de la derechiahabiencia',
 'Entidad de ocurrencia',
 'Descripción de la entidad de ocurrencia',
 'Municipio de ocurrencia',
 'Descrición del municipio de ocurrencia',
 'Localidad de ocurrencia',
 'Descrición de la localidad de ocurrencia',
 'Sitio donde ocurrio la defunción',
 'Descripción del sitio donde ocurrio la defunción',
 'Año de la defunción',
 'Mes de la defunción',
 'Descrición del mes de la defunción',
 'Día de la defunción',
 'Hora de la defunción',
 'Minutos de la defunción',
 'Asistencia médica',
 'Descripción de la asistencia médica',
 'Causa CIE a  cuarto dígito',
 'Descrición de la causa CIE',
 'Quien certificó',
 'Descrición de quien certificó',
 'Entidad de registro',
 'Descrición de la entidad de registro',
 'Municipio de registro',
 'Descrición del municipio de registro',
 'Año de registro',
 'Mes de registro',
 'Descripción del mes de registro',
 'Día de registro',
 'Año de la certificación',
 'Mes de la certificación',
 'Descripció del mes de la certificación',
 'Día de la certificación',
 'Año de la base de datos',
 'Razón de mortalidad materna',
 'Descrición de la razón de mortalidad materna']

In [39]:
pd.DataFrame(Examen)

,Año de nacimiento,Mes de nacimiento,Descripción del mes de nacimiento,Día de nacimiento,Genero,Clave de la edad,Edad cumplida,Estado conyugal,Descripción del estado conyugal,Entidad de residencia,...,Mes de registro,Descripción del mes de registro,Día de registro,Año de la certificación,Mes de la certificación,Descripció del mes de la certificación,Día de la certificación,Año de la base de datos,Razón de mortalidad materna,Descrición de la razón de mortalidad materna
0,1972,6,JUNIO,25,2,A,29,5,CASADO,31,...,1,ENERO,20,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
1,1967,2,FEBRERO,1,2,A,35,5,CASADO,31,...,7,JULIO,28,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
2,1973,6,JUNIO,21,2,A,29,5,CASADO,31,...,10,OCTUBRE,24,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
3,1966,1,ENERO,23,2,A,36,5,CASADO,31,...,10,OCTUBRE,20,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
4,1975,0,NO ESPECIFICADO,0,2,A,30,5,CASADO,9,...,4,ABRIL,8,2005.0,4,ABRIL,8.0,2005,1,Muertes Maternas para la razón de Mortalidad M...
5,1975,0,NO ESPECIFICADO,0,2,A,30,5,CASADO,9,...,4,ABRIL,29,2005.0,4,ABRIL,29.0,2005,1,Muertes Maternas para la razón de Mortalidad M...
6,1985,0,NO ESPECIFICADO,0,2,A,20,5,CASADO,15,...,5,MAYO,18,2005.0,5,MAYO,17.0,2005,1,Muertes Maternas para la razón de Mortalidad M...
7,1978,7,JULIO,9,2,A,27,5,CASADO,15,...,10,OCTUBRE,9,2005.0,10,OCTUBRE,8.0,2005,1,Muertes Maternas para la razón de Mortalidad M...
8,1958,9,SEPTIEMBRE,29,2,A,43,5,CASADO,32,...,1,ENERO,0,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
9,1970,5,MAYO,24,2,A,31,5,CASADO,32,...,4,ABRIL,0,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
10,1972,4,ABRIL,28,2,A,31,5,CASADO,3,...,9,SEPTIEMBRE,20,NaN,0,NO ESPECIFICADO,NaN,2003,1,Muertes Maternas para la razón de Mortalidad M...
11,1966,1,ENERO,6,2,A,35,5,CASADO,11,...,1,ENERO,5,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
12,1969,0,NO ESPECIFICADO,0,2,A,39,5,CASADO,16,...,2,FEBRERO,22,2008.0,2,FEBRERO,21.0,2008,1,Muertes Maternas para la razón de Mortalidad M...
13,1973,0,NO ESPECIFICADO,0,2,A,29,5,CASADO,30,...,3,MARZO,24,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
14,1960,4,ABRIL,21,2,A,45,5,CASADO,27,...,6,JUNIO,8,2005.0,6,JUNIO,8.0,2005,0,Muertes Maternas excluidas para la razón de Mo...
15,1963,2,FEBRERO,16,2,A,42,5,CASADO,7,...,7,JULIO,12,2005.0,7,JULIO,11.0,2005,1,Muertes Maternas para la razón de Mortalidad M...
16,1988,0,NO ESPECIFICADO,0,2,A,17,5,CASADO,28,...,3,MARZO,4,2005.0,2,FEBRERO,28.0,2005,1,Muertes Maternas para la razón de Mortalidad M...
17,1978,0,NO ESPECIFICADO,0,2,A,35,5,CASADO,7,...,2,FEBRERO,27,2013.0,2,FEBRERO,27.0,2013,1,Muertes Maternas para la razón de Mortalidad M...
18,1974,0,NO ESPECIFICADO,0,2,A,39,0,SE IGNORA,18,...,5,MAYO,17,2013.0,5,MAYO,16.0,2013,1,Muertes Maternas para la razón de Mortalidad M...
19,1970,8,AGOSTO,25,2,A,43,5,CASADO,15,...,9,SEPTIEMBRE,11,2013.0,9,SEPTIEMBRE,10.0,2013,1,Muertes Maternas para la razón de Mortalidad M...
20,1974,2,FEBRERO,16,2,A,38,5,CASADO,12,...,1,ENERO,2,2012.0,12,DICIEMBRE,12.0,2012,1,Muertes Maternas para la razón de Mortalidad M...
21,1977,5,MAYO,20,2,A,36,5,CASADO,15,...,9,SEPTIEMBRE,17,2013.0,9,SEPTIEMBRE,16.0,2013,0,Muertes Maternas excluidas para la razón de Mo...
22,1983,4,ABRIL,29,2,A,26,5,CASADO,20,...,2,FEBRERO,17,2009.0,2,FEBRERO,16.0,2009,1,Muertes Maternas para la razón de Mortalidad M...
23,1992,3,MARZO,8,2,A,17,5,CASADO,30,...,12,DICIEMBRE,6,2009.0,12,DICIEMBRE,5.0,2009,1,Muertes Maternas para la razón de Mortalidad M...
24,1989,3,MARZO,0,2,A,21,5,CASADO,7,...,3,MARZO,5,2010.0,3,MARZO,5.0,2010,1,Muertes Maternas para la razón de Mortalidad M...
25,1987,9,SEPTIEMBRE,16,2,A,22,5,CASADO,30,...,11,NOVIEMBRE,29,2009.0,11,NOVIEMBRE,28.0,2009,1,Muertes Maternas para la razón de Mortalidad M...
26,1966,9,SEPTIEMBRE,28,2,A,45,5,CASADO,18,...,10,OCTUBRE,10,2011.0,10,OCTUBRE,9.0,2011,1,Muertes Maternas para la razón de Mortalidad M...
27,1968,10,OCTUBRE,1,2,A,43,5,CASADO,21,...,11,NOVIEMBRE,14,2011.0,11,NOVIEMBRE,14.0,2011,1,Muertes Maternas para la razón de Mortalidad M...
28,1985,0,NO ESPECIFICADO,0,2,A,26,5,CASADO,23,...,5,MAYO,20,2011.0,5,MAYO,20.0,2011,1,Muertes Maternas para la razón de Mortalidad M...
29,1971,8,AGOSTO,14,2,A,40,5,CASADO,30,...,12,DICIEMBRE,16,2011.0,12,DICIEMBRE,15.0,2011,1,Muertes Maternas para la razón de Mortalidad M...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17202,1990,12,DICIEMBRE,19,2,A,25,1,SOLTERO,30,...,10,OCTUBRE,21,2016.0,10,OCTUBRE,20.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17203,1977,8,AGOSTO,30,2,A,39,5,CASADO,30,...,9,SEPTIEMBRE,0,2016.0,9,SEPTIEMBRE,3.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17204,1988,11,NOVIEMBRE,25,2,A,27,5,CASADO,30,...,10,OCTUBRE,0,2016.0,10,OCTUBRE,28.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17205,1986,1,ENERO,12,2,A,30,4,UNION LIBRE,30,...,12,DICIEMBRE,19,2016.0,12,DICIEMBRE,19.0,2016,0,Muertes Maternas excluidas para la razón de Mo...
17206,1985,2,FEBRERO,16,2,A,31,5,CASADO,31,...,5,MAYO,8,2016.0,5,MAYO,8.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17207,1982,8,AGOSTO,29,2,A,33,5,CASADO,31,...,5,MAYO,22,2016.0,5,MAYO,21.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17208,1986,5,MAYO,3,2,A,30,5,CASADO,23,...,6,JUNIO,29,2016.0,6,JUNIO,29.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17209,1999,7,JULIO,22,2,A,16,1,SOLTERO,31,...,7,JULIO,3,2016.0,7,JULIO,3.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17210,1982,3,MARZO,4,2,A,34,2,VIUDO,31,...,7,JULIO,15,2016.0,7,JULIO,15.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17211,2000,8,AGOSTO,9,2,A,16,4,UNION LIBRE,31,...,9,SEPTIEMBRE,14,2016.0,9,SEPTIEMBRE,14.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17212,1989,9,SEPTIEMBRE,20,2,A,26,4,UNION LIBRE,31,...,9,SEPTIEMBRE,16,2016.0,9,SEPTIEMBRE,16.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17213,1995,10,OCTUBRE,20,2,A,21,4,UNION LIBRE,31,...,11,NOVIEMBRE,22,2016.0,11,NOVIEMBRE,21.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17214,1984,12,DICIEMBRE,3,2,A,32,5,CASADO,4,...,12,DICIEMBRE,14,2016.0,12,DICIEMBRE,14.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17215,1995,4,ABRIL,8,2,A,21,1,SOLTERO,31,...,12,DICIEMBRE,29,2016.0,12,DICIEMBRE,29.0,2016,0,Muertes Maternas excluidas para la razón de Mo...
17216,1990,8,AGOSTO,13,2,A,25,4,UNION LIBRE,32,...,1,ENERO,6,2016.0,1,ENERO,3.0,2016,0,Muertes Maternas excluidas para la razón de Mo...
17217,1988,9,SEPTIEMBRE,20,2,A,27,4,UNION LIBRE,32,...,5,MAYO,12,2016.0,5,MAYO,6.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17218,1992,10,OCTUBRE,17,2,A,23,4,UNION LIBRE,32,...,6,JUNIO,1,2016.0,6,JUNIO,1.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17219,1987,5,MAYO,30,2,A,29,5,CASADO,1,...,10,OCTUBRE,26,2016.0,10,OCTUBRE,23.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17220,2000,6,JUNIO,23,2,A,16,1,SOLTERO,32,...,11,NOVIEMBRE,14,2016.0,11,NOVIEMBRE,12.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17221,1989,5,MAYO,1,2,A,27,4,UNION LIBRE,32,...,11,NOVIEMBRE,10,2016.0,11,NOVIEMBRE,10.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17222,1989,5,MAYO,12,2,A,27,4,UNION LIBRE,32,...,12,DICIEMBRE,29,2016.0,12,DICIEMBRE,25.0,2016,0,Muertes Maternas excluidas para la razón de Mo...
17223,1979,7,JULIO,14,2,A,37,5,CASADO,30,...,11,NOVIEMBRE,25,2016.0,11,NOVIEMBRE,24.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17224,1989,12,DICIEMBRE,23,2,A,26,1,SOLTERO,30,...,8,AGOSTO,29,2016.0,8,AGOSTO,28.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17225,1993,6,JUNIO,8,2,A,23,4,UNION LIBRE,30,...,7,JULIO,11,2016.0,7,JULIO,10.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17226,1989,8,AGOSTO,2,2,A,27,1,SOLTERO,30,...,12,DICIEMBRE,7,2016.0,12,DICIEMBRE,6.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17227,1995,10,OCTUBRE,6,2,A,20,1,SOLTERO,31,...,7,JULIO,11,2016.0,7,JULIO,11.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17228,1971,11,NOVIEMBRE,14,2,A,45,5,CASADO,32,...,12,DICIEMBRE,14,2016.0,12,DICIEMBRE,8.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17229,1994,11,NOVIEMBRE,26,2,A,21,1,SOLTERO,31,...,1,ENERO,2,2016.0,1,ENERO,2.0,2016,1,Muertes Maternas para la razón de Mortalidad M...
17230,1976,5,MAYO,12,2,A,39,5,CASADO,32,...,1,ENERO,25,2016.0,1,ENERO,21.0,2016,0,Muertes Maternas excluidas para la razón de Mo...
17231,1990,8,AGOSTO,20,2,A,25,5,CASADO,32,...,4,ABRIL,7,2016.0,4,ABRIL,4.0,2016,1,Muertes Maternas para la razón de Mortalidad M...

In [20]:
Examen=Examen.drop(['Año de nacimiento','Mes de nacimiento','Descripción del mes de nacimiento','Genero','Clave de la edad','Estado conyugal','Entidad de residencia','Día de nacimiento','Descripción de entidad de residencia','Municipio de residencia','Descripción del municipio de residencia','Localidad de residencia','Descripción del tamaño de localidad','Mes de registro','Descripción del mes de registro','Día de registro','Descripión de la localidad de residencia','Ocupación habitual','Descripción de la ocupación habitual','Escolaridad','Descripción de la escolaridad','Derechiahabiencia','Descrición de la derechiahabiencia','Municipio de registro','Descrición del municipio de registro','Año de registro','Año de la certificación','Mes de la certificación','Descripció del mes de la certificación','Día de la certificación','Año de la base de datos','Razón de mortalidad materna','Descrición de la razón de mortalidad materna','Entidad de ocurrencia','Descripción de la entidad de ocurrencia','Municipio de ocurrencia','Descrición del municipio de ocurrencia','Sitio donde ocurrio la defunción','Hora de la defunción','Minutos de la defunción','Asistencia médica','Descripción de la asistencia médica','Descrición de la causa CIE','Quien certificó','Descrición de quien certificó','Entidad de registro','Descrición de la entidad de registro','Descripción del sitio donde ocurrio la defunción','Año de la defunción','Mes de la defunción','Descrición del mes de la defunción','Día de la defunción'],axis=1)

In [21]:
pd.DataFrame(Examen)

,Edad cumplida,Descripción del estado conyugal,Tamaño de localidad,Localidad de ocurrencia,Descrición de la localidad de ocurrencia,Causa CIE a cuarto dígito
0,29,CASADO,9,1,311020001 Valladolid,O994
1,35,CASADO,9,1,310500001 Mérida,O141
2,29,CASADO,4,1,310560001 Oxkutzcab,O159
3,36,CASADO,1,1,310500001 Mérida,O159
4,30,CASADO,0,0,090160000 No especificado,O266
5,30,CASADO,0,0,090120000 No especificado,O717
6,20,CASADO,12,0,150580000 No especificado,O364
7,27,CASADO,15,1,150570001 Naucalpan de Juárez,O141
8,43,CASADO,1,1,320170001 Guadalupe,O16X
9,31,CASADO,13,1,320560001 Zacatecas,O141
10,31,CASADO,13,1,030030001 La Paz,O985
11,35,CASADO,3,1,110200001 León de los Aldama,O021
12,39,CASADO,3,1,160530001 Morelia,O150
13,29,CASADO,9,1,301180001 Orizaba,O985
14,45,CASADO,14,1,270040001 Villahermosa,O96X
15,42,CASADO,1,1,270040001 Villahermosa,O85X
16,17,CASADO,14,1,280220001 Heroica Matamoros,O994
17,35,CASADO,1,126,070400126 Aztlán,O141
18,39,SE IGNORA,14,1,180170001 Tepic,O871
19,43,CASADO,15,1,150580001 Ciudad Nezahualcóyotl,O241
20,38,CASADO,13,1,120290001 Chilpancingo de los Bravo,O994
21,36,CASADO,14,1,151040001 Tlalnepantla,O96X
22,26,CASADO,1,1,301930001 Veracruz,O648
23,17,CASADO,14,1,301930001 Veracruz,O85X
24,21,CASADO,1,656,070520656 Buenavista,O141
25,22,CASADO,6,1,301930001 Veracruz,O995
26,45,CASADO,14,1,180170001 Tepic,O141
27,43,CASADO,13,1,211560001 Tehuacán,O994
28,26,CASADO,15,1,230050001 Cancún,O364
29,40,CASADO,6,1,300870001 Xalapa-Enríquez,O994
...,...,...,...,...,...,...
17202,25,SOLTERO,5,1,301930001 Veracruz,O150
17203,39,CASADO,1,97,301750097 Ojo de Agua,O722
17204,27,CASADO,8,1,301310001 Poza Rica de Hidalgo,O718
17205,30,UNION LIBRE,5,1,301930001 Veracruz,O960
17206,31,CASADO,4,1,310500001 Mérida,O364
17207,33,CASADO,5,1,311020001 Valladolid,O432
17208,30,CASADO,1,1,311020001 Valladolid,O720
17209,16,SOLTERO,4,1,310500001 Mérida,O996
17210,34,VIUDO,4,1,310500001 Mérida,O998
17211,16,UNION LIBRE,15,1,310500001 Mérida,O234
17212,26,UNION LIBRE,5,1,310500001 Mérida,O996
17213,21,UNION LIBRE,15,1,310500001 Mérida,O998
17214,32,CASADO,13,1,310500001 Mérida,O985
17215,21,SOLTERO,6,1,310530001 Muna,C58X
17216,25,UNION LIBRE,2,1,320560001 Zacatecas,O961
17217,27,UNION LIBRE,3,1,320170001 Guadalupe,O142
17218,23,UNION LIBRE,1,1,320100001 Fresnillo,O142
17219,29,CASADO,1,1,320520001 Villa García,O998
17220,16,SOLTERO,2,1,320170001 Guadalupe,O150
17221,27,UNION LIBRE,6,1,320100001 Fresnillo,O721
17222,27,UNION LIBRE,5,1,320560001 Zacatecas,O960
17223,37,CASADO,2,1,300470001 Coscomatepec de Bravo,O060
17224,26,SOLTERO,1,1,300440001 Córdoba,O001
17225,23,UNION LIBRE,2,1,301380001 Río Blanco,O998
17226,27,SOLTERO,5,1,300440001 Córdoba,O441
17227,20,SOLTERO,10,1,310500001 Mérida,O900
17228,45,CASADO,2,1,320560001 Zacatecas,O009
17229,21,SOLTERO,5,1,310500001 Mérida,O141
17230,39,CASADO,2,1,320370001 Pánuco,O960
17231,25,CASADO,13,1,320170001 Guadalupe,O142

In [19]:
#¿Cuántos tipos de escolaridad existen?
len(Examen['Edad cumplida'].unique())

50

In [7]:
#¿Cuántas edades diferentes tenían las madres cuando fallecieron?
(Examen['Edad cumplida'].unique())

array([ 29,  35,  36,  30,  20,  27,  43,  31,  39,  45,  42,  17,  38,
        26,  21,  22,  40,  44,  34,  41,  33,  13,  24,  25,  37,  19,
        23,  32,  28, 998,  15,  46,  48,  16,  18,  12,  47,  14,  51,
        50,  54,  49,  11,  53,  81,  70,  82,  59,  86,  65])

In [13]:
Examen.describe()

       Edad cumplida  Tamaño de localidad  Localidad de ocurrencia
count   17232.000000         17232.000000             17232.000000
mean       29.765727             7.823178                17.770195
std        36.916010             5.928247               102.275606
min        11.000000             0.000000                 0.000000
25%        22.000000             2.000000                 1.000000
50%        28.000000             6.000000                 1.000000
75%        34.000000            14.000000                 1.000000
max       998.000000            17.000000              3515.000000

,Edad cumplida,Descripción del estado conyugal,Tamaño de localidad,Localidad de ocurrencia,Descrición de la localidad de ocurrencia,Causa CIE a cuarto dígito
0,29,CASADO,9,1,311020001 Valladolid,O994
1,35,CASADO,9,1,310500001 Mérida,O141
2,29,CASADO,4,1,310560001 Oxkutzcab,O159
3,36,CASADO,1,1,310500001 Mérida,O159
4,30,CASADO,0,0,090160000 No especificado,O266
5,30,CASADO,0,0,090120000 No especificado,O717
6,20,CASADO,12,0,150580000 No especificado,O364
7,27,CASADO,15,1,150570001 Naucalpan de Juárez,O141
8,43,CASADO,1,1,320170001 Guadalupe,O16X
9,31,CASADO,13,1,320560001 Zacatecas,O141
10,31,CASADO,13,1,030030001 La Paz,O985
11,35,CASADO,3,1,110200001 León de los Aldama,O021
12,39,CASADO,3,1,160530001 Morelia,O150
13,29,CASADO,9,1,301180001 Orizaba,O985
14,45,CASADO,14,1,270040001 Villahermosa,O96X
15,42,CASADO,1,1,270040001 Villahermosa,O85X
16,17,CASADO,14,1,280220001 Heroica Matamoros,O994
17,35,CASADO,1,126,070400126 Aztlán,O141
18,39,SE IGNORA,14,1,180170001 Tepic,O871
19,43,CASADO,15,1,150580001 Ciudad Nezahualcóyotl,O241
20,38,CASADO,13,1,120290001 Chilpancingo de los Bravo,O994
21,36,CASADO,14,1,151040001 Tlalnepantla,O96X
22,26,CASADO,1,1,301930001 Veracruz,O648
23,17,CASADO,14,1,301930001 Veracruz,O85X
24,21,CASADO,1,656,070520656 Buenavista,O141
25,22,CASADO,6,1,301930001 Veracruz,O995
26,45,CASADO,14,1,180170001 Tepic,O141
27,43,CASADO,13,1,211560001 Tehuacán,O994
28,26,CASADO,15,1,230050001 Cancún,O364
29,40,CASADO,6,1,300870001 Xalapa-Enríquez,O994
...,...,...,...,...,...,...
17202,25,SOLTERO,5,1,301930001 Veracruz,O150
17203,39,CASADO,1,97,301750097 Ojo de Agua,O722
17204,27,CASADO,8,1,301310001 Poza Rica de Hidalgo,O718
17205,30,UNION LIBRE,5,1,301930001 Veracruz,O960
17206,31,CASADO,4,1,310500001 Mérida,O364
17207,33,CASADO,5,1,311020001 Valladolid,O432
17208,30,CASADO,1,1,311020001 Valladolid,O720
17209,16,SOLTERO,4,1,310500001 Mérida,O996
17210,34,VIUDO,4,1,310500001 Mérida,O998
17211,16,UNION LIBRE,15,1,310500001 Mérida,O234
17212,26,UNION LIBRE,5,1,310500001 Mérida,O996
17213,21,UNION LIBRE,15,1,310500001 Mérida,O998
17214,32,CASADO,13,1,310500001 Mérida,O985
17215,21,SOLTERO,6,1,310530001 Muna,C58X
17216,25,UNION LIBRE,2,1,320560001 Zacatecas,O961
17217,27,UNION LIBRE,3,1,320170001 Guadalupe,O142
17218,23,UNION LIBRE,1,1,320100001 Fresnillo,O142
17219,29,CASADO,1,1,320520001 Villa García,O998
17220,16,SOLTERO,2,1,320170001 Guadalupe,O150
17221,27,UNION LIBRE,6,1,320100001 Fresnillo,O721
17222,27,UNION LIBRE,5,1,320560001 Zacatecas,O960
17223,37,CASADO,2,1,300470001 Coscomatepec de Bravo,O060
17224,26,SOLTERO,1,1,300440001 Córdoba,O001
17225,23,UNION LIBRE,2,1,301380001 Río Blanco,O998
17226,27,SOLTERO,5,1,300440001 Córdoba,O441
17227,20,SOLTERO,10,1,310500001 Mérida,O900
17228,45,CASADO,2,1,320560001 Zacatecas,O009
17229,21,SOLTERO,5,1,310500001 Mérida,O141
17230,39,CASADO,2,1,320370001 Pánuco,O960
17231,25,CASADO,13,1,320170001 Guadalupe,O142

In [27]:
Examen1=Examen.set_index('Edad cumplida')

In [28]:
Examen1.head()

,Descripción del estado conyugal,Tamaño de localidad,Localidad de ocurrencia,Descrición de la localidad de ocurrencia,Causa CIE a cuarto dígito
Edad cumplida,,,,,
29,CASADO,9,1,311020001 Valladolid,O994
35,CASADO,9,1,310500001 Mérida,O141
29,CASADO,4,1,310560001 Oxkutzcab,O159
36,CASADO,1,1,310500001 Mérida,O159
30,CASADO,0,0,090160000 No especificado,O266

In [40]:
#¿Qué entidad tiene mayor número muertes?
len(Examen['Entidad de residencia'].unique())

36

In [41]:
(Examen['Entidad de residencia'].unique())

array([31,  9, 15, 32,  3, 11, 16, 30, 27,  7, 28, 18, 12, 20, 21, 23, 26,
       22, 19, 25,  8, 14, 17, 24, 13, 10,  4, 29,  5,  2,  1,  6, 34, 33,
        0, 35])

In [42]:
Examen=Examen.set_index('Entidad de residencia')

In [43]:
Examen.head()

,Año de nacimiento,Mes de nacimiento,Descripción del mes de nacimiento,Día de nacimiento,Genero,Clave de la edad,Edad cumplida,Estado conyugal,Descripción del estado conyugal,Descripción de entidad de residencia,...,Mes de registro,Descripción del mes de registro,Día de registro,Año de la certificación,Mes de la certificación,Descripció del mes de la certificación,Día de la certificación,Año de la base de datos,Razón de mortalidad materna,Descrición de la razón de mortalidad materna
Entidad de residencia,,,,,,,,,,,,,,,,,,,,,
31,1972,6,JUNIO,25,2,A,29,5,CASADO,Yucatán,...,1,ENERO,20,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
31,1967,2,FEBRERO,1,2,A,35,5,CASADO,Yucatán,...,7,JULIO,28,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
31,1973,6,JUNIO,21,2,A,29,5,CASADO,Yucatán,...,10,OCTUBRE,24,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
31,1966,1,ENERO,23,2,A,36,5,CASADO,Yucatán,...,10,OCTUBRE,20,NaN,0,NO ESPECIFICADO,NaN,2002,1,Muertes Maternas para la razón de Mortalidad M...
9,1975,0,NO ESPECIFICADO,0,2,A,30,5,CASADO,Distrito Federal,...,4,ABRIL,8,2005.0,4,ABRIL,8.0,2005,1,Muertes Maternas para la razón de Mortalidad M...

In [ ]:
#Nota: No supe como manejar la base de datos, tenia muchas columnas y me di cuenta que si no me aparecian en los encabezados npor esome marcaba error y me decia que no existia el dato!!! me di cuenta muy tarde